<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DHKQNOK" failures="0" tests="4" name="com.tce.qa.testcases.LoginWithUserIDPasswordTest" time="0.004" errors="1" timestamp="07 Aug 2019 06:23:48 GMT" skipped="3">
  <testcase classname="com.tce.qa.testcases.LoginWithUserIDPasswordTest" name="setup" time="0.004">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.tce.qa.base.TestBase.initialization(TestBase.java:32)
at com.tce.qa.testcases.LoginWithUserIDPasswordTest.setup(LoginWithUserIDPasswordTest.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
    </error>
  </testcase> <!-- setup -->
  <testcase classname="com.tce.qa.testcases.LoginWithUserIDPasswordTest" name="loginWithUserIDPasswordPageTitle" time="0.000">
    <skipped/>
  </testcase> <!-- loginWithUserIDPasswordPageTitle -->
  <testcase classname="com.tce.qa.testcases.LoginWithUserIDPasswordTest" name="loginWithUserIDPasswordPageLogo" time="0.000">
    <skipped/>
  </testcase> <!-- loginWithUserIDPasswordPageLogo -->
  <testcase classname="com.tce.qa.testcases.LoginWithUserIDPasswordTest" name="loginWithUserIDPassword" time="0.000">
    <skipped/>
  </testcase> <!-- loginWithUserIDPassword -->
</testsuite> <!-- com.tce.qa.testcases.LoginWithUserIDPasswordTest -->
